from tkinter import *
root=Tk()
def file():
    f=open("data.txt","a+")
    n2=name.get()
    e2=email.get()
    m2=mobile.get()
    g2=var.get()
    c2=c1.get()
    f.write("Name:"+n2+"\n"+"Email:"+e2+"\n"+"Mobile:"+str(m2)+"\n"+"Gender:"+g2+"\n"+"City:"+c2)
    #print(info)
var=StringVar()
var.set("m")
c1=StringVar()
c1.set("Lucknow")
options=["Lucknow","Prayagraj","Banaras","Kanpur"]
root.title("login form")
root.geometry("450x370+400+50")
frame2=LabelFrame(root ,text="Registration",border=0,font=("Arial 20 bold"),labelanchor="n", height=370,width=450,bg="blue")
frame2.place(x=0,y=0)
frame=LabelFrame(frame2 , height=300,width=100,bg="red")
frame.place(x=0,y=0)
frame1=LabelFrame(frame2 , height=300,width=350,bg="green")
frame1.place(x=100,y=0)

name=Entry(frame1,width=30,font=("Arial,20,bold"),borderwidth="4")
name.place(x=30,y=50)
email=Entry(frame1,width=30,font=("Arial,20,bold"),borderwidth="4")
email.place(x=30,y=100)
mobile=Entry(frame1,width=30,font=("Arial,20,bold"),borderwidth="4")
mobile.place(x=30,y=150)
gender=Radiobutton(frame1,text="Male",bg="green",font=("Arial,20,bold"),width=10,variable=var,value="m")
gender.place(x=30,y=200)
gender=Radiobutton(frame1,width=10,text="Female",bg="green"  ,variable=var,value="f",font=("Arial,20,bold"))
gender.place(x=190,y=200)
city=OptionMenu(frame1,c1,*options)
city.place(x=30,y=250)
n1=Label(frame,text="Name: ",bg="red",fg="black",font=("Arial,20,bold"))
n1.place(x=30,y=50)
e1=Label(frame,text="Email: ",bg="red",fg="black",font=("Arial,20,bold"))
e1.place(x=30,y=100)
m1=Label(frame,text="Mobile: ",bg="red",fg="black",font=("Arial,20,bold"))
m1.place(x=30,y=150)
g=Label(frame,text="Gender: ",bg="red",fg="black",font=("Arial,20,bold"))
g.place(x=30,y=200)
c=Label(frame,text="City: ",bg="red",fg="black",font=("Arial,20,bold"))
c.place(x=30,y=250)
btns=Button(frame2,font=("Arial 10 bold"),bg="blue",fg="white",text="Submit",borderwidth=6,command=file)
btns.place(x=180,y=300)
root.mainloop()